### ISSUE TITLE
My next episodes lists unaired episodes

### ISSUE THREAD

**Issue by keyos1** [charly3pins/quasar#2]
[shows.go.txt](https://github.com/charly3pins/quasar/files/1351376/shows.go.txt)
First of all, thanks a lot for continuing development and expanding features.

Now to the issue: when you go to "My next episodes" it creates list based on NextEpisode of the show.
However there's no check whether the episode was aired or not, so you get a bunch of episodes without ability to watch them.

The workaround I used was to check whether watchedProgressShow.Aired is greater than watchedProgressShow.Completed. This way you know you have episodes that were aired but not watched

Attached is the diff between last trakt/shows.go and my workaround

Also I have couple of other ideas, but am not sure if there's forum we can discuss them.
If you would like, please let me know how can we discuss new features and some changes.

Thanks a lot
Stas

**Comment by charly3pins** [comment]
Hi @keyos1 , nice catch with this .Aired parameter, I think it will help us to hide the unaired episodes. I'll try to add it this week and release new version.
If you have more comments and suggestions, you can create new issue for talking there as a forum in a single post

**Comment by keyos1** [comment]
I actually compiled it with my change and it looks fine. Now I'm working on understanding how to cache fan art and overviews for single episodes so it will be populated in the lists. Because now you get "no information available"

**Comment by charly3pins** [comment]
You can create a PR if you want with this change, and I'll merge it later to add it in the next version

**Comment by charly3pins** [comment]
@keyos1 did you added this changes in the pull request that you've done?

**Comment by keyos1** [comment]
Yep, the pull request contained this too
