### ISSUE TITLE
New updates

### ISSUE THREAD

**Issue by keyos1** [charly3pins/quasar#3]
Hello again.

This time I'm adding fairly large list of changes. Please let me know if this format is ok with you or you would prefer working with pulls.

Here it goes:

Files:

[trakt_movies.go.txt](https://github.com/charly3pins/quasar/files/1377601/trakt_movies.go.txt)
[trakt_shows.go.txt](https://github.com/charly3pins/quasar/files/1377602/trakt_shows.go.txt)
[trakt_trakt.go.txt](https://github.com/charly3pins/quasar/files/1377603/trakt_trakt.go.txt)
[xbmc_types.go.txt](https://github.com/charly3pins/quasar/files/1377604/xbmc_types.go.txt)
[api_index.go.txt](https://github.com/charly3pins/quasar/files/1377605/api_index.go.txt)
[api_movies.go.txt](https://github.com/charly3pins/quasar/files/1377606/api_movies.go.txt)
[api_routes.go.txt](https://github.com/charly3pins/quasar/files/1377607/api_routes.go.txt)
[api_shows.go.txt](https://github.com/charly3pins/quasar/files/1377608/api_shows.go.txt)
[api_trakt.go.txt](https://github.com/charly3pins/quasar/files/1377609/api_trakt.go.txt)
[bittorrent_player.go.txt](https://github.com/charly3pins/quasar/files/1377610/bittorrent_player.go.txt)
[strings.po.txt](https://github.com/charly3pins/quasar/files/1377611/strings.po.txt)

Changes:

in plugin.video.quasar\resources\language\English\strings.po added 6 more strings:
======================================================
msgctxt "#30309"
msgid "My Movies"
msgstr ""

msgctxt "#30310"
msgid "My TV Shows"
msgstr ""

msgctxt "#30311"
msgid "Shows"
msgstr ""

msgctxt "#30312"
msgid "Progress"
msgstr ""

msgctxt "#30313"
msgid "Mark Watched in Trakt"
msgstr ""

msgctxt "#30314"
msgid "Mark Unwatched in Trakt"
msgstr ""

api/index.go:
=============
- added "My Movies" and "My TV Shows" to main index to allow direct entry to trakt submenus

api/movies.go:
==============
- removed "Trakt" from the index
- rewrote contextMenu creation in renderMovies
- added context menu to mark movie watched or unwatched in Trakt depending on it's status from cache
- marked movies watched in overlay depending on status from cache

api/routes.go:
==============
- added routes to mark watched/unwatched in trakt to movies/shows/seasons/episodes (not using all for now)
- removed /youtube route (changed all trailer URLs to use plugin.video.youtube instead, because it is well maintained)

api/shows.go:
=============
- removed "Trakt" from the index
- moved "My next episodes" to top and renamed it to "Progress" (also using localization for labels)
- renamed "My shows" to "Shows" using localization
- rewrote ListItem.Info.Trailer to use plugin.video.youtube in various functions
- rewrote contextMenu creation in various functions
- added context menu to mark movie watched or unwatched in trakt depending on it's status from cache
- marked episodes watched in overlay depending on status from cache

api/trakt.go:
=============
- added inMoviesWatched function that uses cache to check whether movie was watched in trakt or not
- added inEpisodesWatched function that uses cache to check whether movie was watched in trakt or not
- added MarkMovieWatchedInTrakt, MarkMovieUnwatchedInTrakt, MarkShowWatchedInTrakt, MarkShowUnwatchedInTrakt,
  MarkSeasonWatchedInTrakt, MarkSeasonUnwatchedInTrakt, MarkEpisodeWatchedInTrakt, MarkEpisodeUnwatchedInTrakt to
  allow marking from context menus. For now only using functions for episodes and movies
- rewrote ListItem.Info.Trailer to use plugin.video.youtube in various functions
- rewrote contextMenu creation in various functions
- added context menu to mark movie/episode watched or unwatched in trakt depending on it's status from cache
- marked movies/episodes watched in overlay depending on status from cache
- rewrote renderProgressShows to allow pulling correct episode fanarts and details

bittorrent/player.go:
=====================
- moved progress update out of the if clause to allow update even when the torrent file wasn't deleted

trakt/movies.go:
================
- added WatchedMovies function to populate cache of movies watched in trakt

trakt/shows.go:
===============
- added WatchedEpisodes function to populate cache of episodes watched in trakt
- modified WatchedShows to pull full show info. This way it is possible to populate "My shows" with show info
- rewrote WatchedProgressShows to use goroutines to pull show progress info in parallel for all shows. this really
  speeds up the fetch. Also used WatchedProgressShow.Aired/Completed to only append aired episodes

trakt/trakt.go:
===============
- added/modified various types to allow better Watched information processing
- added AddEpisodeToWatchedHistory2, RemoveEpisodeFromWatchedHistory2, AddMovieToWatchedHistory2,
  RemoveMovieFromWatchedHistory2 to actually interface with trakt for watched/unwatched marking

xbmc/types.go:
==============
- fixed IconOverlay enumeration. For some reason it was missing IconOverlayUnwatched

**Comment by keyos1** [comment]
Forgot to tell that I was testing it on Windows 10 machine and it seems to work pretty fine

**Comment by charly3pins** [comment]
@keyos1 thanks for your collaboration, but working with .txt files is not the correct way. I prefer pull requests in order to review the changes, test them and then merge to the master and release a new version with them. So please, open a pull request for #2 because I think you had done and works pretty well and then open a pull request for resolve this one. I think it's better than having multiple .txt files to add manually for me and no review process which is important in this case for the multiple changes you want to introduce.
Thanks

**Comment by keyos1** [comment]
So, I'm new to git interface and when I tried to create pull it redirected me to scakemyer's repo to merge your commit with his. Do I need to fork this project to my own repo and do commits there in order to make pulls with your fork ?
Sorry for the confusion :)

**Comment by charly3pins** [comment]
Yes, you have to fork this repo , not the other one, otherwise you cannot pull request on this. Don't worry for asking doubts!
