### ISSUE TITLE
util.Version and other problems after renaming github.com/scakemyer/quasar to github.com/charly3pins/quasar

### ISSUE THREAD

**Issue by keyos1** [charly3pins/quasar#5]
Hi,
so after pulling latest repository and trying to compile I got .exe crashing on trying to output version number on startup.
This was caused by a change you made to Makefile to declare the GO_PKG:
GO_PKG = github.com/charly3pins/quasar
which made the reference to util.Version belong to this package while imports go from
github.com/scakemyer/quasar/util
After changing imports to become github.com/charly3pins/quasar/util this went ok, but then I got
crashes in config.Get() immediately after config reload
The only difference between working and crashing version was the GO_PKG change and 3 more (I think)
import changes to github.com/charly3pins/quasar packages, so I just went and replaced all
github.com/scakemyer/quasar imports with github.com/charly3pins/quasar (except libtorrent-go)
and everything went working back normally.
I can commit these to my repo and make pull request or wait for you to finish merge and change these too.
Please let me know
Thanks

**Comment by charly3pins** [comment]
Yes,  I changed this imports locally too. You can create the pull request for this issue too. I will review the pull requests tonight, so if you do this one too would be nice.
Thanks
